version: '3'

services:
    php:
        build:
            context: docker/php
        ports:
            - 9000:9000
        volumes:
            - .:/srv/www/msatbsx_project
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./docker/php/.bashrc:/root/.bashrc
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /srv/www/msatbsx_project
        environment:
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: secret

    nginx:
        image: nginx:1.13.8
        ports:
            - 80:80
        volumes:
            - .:/srv/www/msatbsx_project
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
 
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        depends_on:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: website
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: secret
            TERM: xterm
